/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#839493",
              "on-surface": "#e5e2e1",
              "on-secondary": "#313030",
              "tertiary-fixed": "#d4e6e5",
              "surface-container-highest": "#353534",
              "surface-dim": "#131313",
              "surface-variant": "#353534",
              "on-secondary-fixed": "#1c1b1b",
              "on-primary-container": "#541100",
              "surface-tint": "#ffb5a0",
              "secondary-fixed-dim": "#c8c6c5",
              "on-primary": "#601400",
              "secondary-fixed": "#e5e2e1",
              "inverse-on-surface": "#313030",
              "primary": "#ffb5a0",
              "on-secondary-container": "#bab8b7",
              "outline-variant": "#5d4038",
              "surface-container-lowest": "#0e0e0e",
              "surface-container": "#201f1f",
              "secondary-container": "#4a4949",
              "surface-container-low": "#1c1b1b",
              "secondary": "#c8c6c5",
              "on-surface-variant": "#e7bdb2",
              "on-tertiary": "#233333",
              "background": "#131313",
              "outline": "#ad887e",
              "on-tertiary-fixed": "#0e1e1e",
              "primary-fixed": "#ffdbd1",
              "tertiary-fixed-dim": "#b8cac9",
              "primary-fixed-dim": "#ffb5a0",
              "on-tertiary-container": "#1d2c2c",
              "on-secondary-fixed-variant": "#474646",
              "surface": "#131313",
              "error-container": "#93000a",
              "primary-container": "#ff5625",
              "surface-bright": "#3a3939",
              "on-tertiary-fixed-variant": "#3a4a49",
              "on-error-container": "#ffdad6",
              "inverse-primary": "#b12d00",
              "on-error": "#690005",
              "tertiary": "#b8cac9",
              "error": "#ffb4ab",
              "surface-container-high": "#2a2a2a",
              "inverse-surface": "#e5e2e1",
              "on-primary-fixed": "#3b0900",
              "on-primary-fixed-variant": "#872000",
              "on-background": "#e5e2e1"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"],
              "mono": ["Roboto Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
